force-app/main/default/objects/Launch_Async_Class__e/Launch_Async_Class__e.object-meta.xml
<CustomObject>
    <label>Launch Async Class</label>
    <pluralLabel>Launch Async Class</pluralLabel>
</CustomObject>

force-app/main/default/objects/Launch_Async_Class__e/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TrevorQueueableClass.cls
public class TrevorQueueableClass implements Queueable {

    public void execute(QueueableContext context) { 

        // Can't queue 2 asynchronous jobs while in async context
        System.enqueueJob(new ShakeItAllAboutQueueable());
        System.enqueueJob(new DoTheHokeyPokeyQueueable());

        // But you can publish 2 platform events that in turn each kick off a queueable job. In fact you can publish 10,000 platform events
        // List<Launch_Async_Class__e> asyncJobEvents = new List<Launch_Async_Class__e>();
        // asyncJobEvents.add(new Launch_Async_Class__e(Class_Name__c='ShakeItAllAboutQueueable'));
        // asyncJobEvents.add(new Launch_Async_Class__e(Class_Name__c='DoTheHokeyPokeyQueueable'));
        // EventBus.publish(asyncJobEvents); 
    } 

}